import { Inter } from "next/font/google";
import "./globals.css";

import ScrollToTop from "./components/scrollToTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Personal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <ScrollToTop />
      </body>
    </html>
  );
}
