import { Inter } from "next/font/google";
import "../../styles/global.scss";
// import "../globals.css";


import ScrollToTop from "../components/scrollToTop";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Personal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <ScrollToTop />
      </body>
    </html>
  );
}
