import React from "react";
import { Inter } from "next/font/google";

import "../../styles/global.scss";

import "bootstrap/dist/css/bootstrap.min.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import Navbar from "@/app/components/Navbar";
import CustomCursor from "@/app/components/MouseCursor";
import Aos from "@/app/components/AOS";
import Footer from "@/app/components/Footer";
import ScrollToTop from "@/app/components/scrollToTop";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Personal",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Aos />
        <Navbar />
        <div id="smooth-content">
          <main>{children}</main>
        </div>
        <Footer />
        <CustomCursor />
        <div id="portal"></div>
        <ScrollToTop />
      </body>
    </html>
  );
}
